popup_agree_button_message: Hyväksy
disagree_button_label: 'Ei kiitos'
popup_hide_button_message: Piilossa
withdraw_tab_button_label: Tietosuoja-asetukset
accept_all_categories_button_label: 'Hyväksy kaikki evästeet'
