_core:
  default_config_hash: 3ooO-bLkru7Jl91Kb8hO7pD1divveu98PTIZQiCV3pQ
langcode: en
site_settings:
  default_icon: group
  theme_color: suomenlinna
  koro: wave
footer_settings:
  footer_color: dark
