_core:
  default_config_hash: wndI7XxZzH2TMe66dJgFiRSUoYoyaRHiTbEFsg3nYso
client_key: ''
environment: ''
release: ''
log_levels:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
  6: 0
  7: 0
  8: 0
stack: true
timeout: !!float 2
message_limit: 2048
trace: false
fatal_error_handler: false
fatal_error_handler_memory: 2560
javascript_error_handler: false
drush_error_handler: false
public_dsn: ''
ssl: verify_ssl
ca_cert: ''
ignored_channels: {  }
send_user_data: false
rate_limit: 0
send_request_body: false
request_tracing: false
traces_sample_rate: null
browser_traces_sample_rate: null
database_tracing: false
twig_tracing: false
auto_session_tracking: false
send_client_reports: false
drush_tracing: true
seckit_set_report_uri: false
send_monitoring_sensor_status_changes: false
404_tracing: false
show_report_dialog: false
error_embed_url: ''
tunnel: false
modules: false
cron_monitor_id: ''
profiles_sample_rate: null
disable_deprecated_alter: true
send_inp_spans: false
